services:
  app:
    image: nasgunawan/simades-prod:latest
    container_name: simades-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - internal-stack-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: simades-web
    restart: unless-stopped
    volumes:
      - .:/var/www:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo 'server {
            listen 80;
            root /var/www/public;
            index index.php;
            location / { try_files $$uri $$uri/ /index.php?$$query_string; }
            location ~ \.php$$ {
                include fastcgi_params;
                fastcgi_pass app:9000;
                fastcgi_param SCRIPT_FILENAME $$document_root$$fastcgi_script_name;
            }
        }' > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'
    networks:
      - npm-network
      - internal-stack-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: simades-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: simades_db
      MYSQL_ROOT_PASSWORD: safe_vps_password_123
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - internal-stack-network

networks:
  npm-network:
    external: true
    name: proxy-network
  internal-stack-network:
    driver: bridge

volumes:
  db-volume:
