name: Build and Push Docker Image

on:
  push:
<<<<<<< HEAD
    branches: [ "master" ] # Triggers only when you push to your main branch
=======
    branches: [ "main" ] # Triggers only when you push to your main branch
>>>>>>> 2f44cd8e3295bb6c24604447400620cc64df2ef3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/simades-prod:latest
